### ISSUE TITLE
Implementation Query

### ISSUE THREAD

**Issue by OldManMeta** [donmccurdy/glTF-Transform-View#81]
Hi Don, truly awesome and amazing work on all your projects. I found this when reviewing the glTF-Transform docs.

No issues (yet) - sorry, didn't know how else to reach out (Discord?)

As you stated, the intention with the glTF-Transform-View is for editing experiences, which is precisely how I got here with what I am developing. In particular, I wanted to be able to export glTF models after editing with Draco encoding - but this View project really caught my eye!

In my project, I'm using TS in a React environment, using React-Three-Fiber as well as some areas where I am using just plain old Three.js for specific scenarios.

I'm still learning all of this - so not knowledgeable enough at the moment to have a clear mental model in my head about how to integrate your solution.

Is the documentView intended to be a wrapper around the glTF model, providing an easier editing experience of the underlying asset?

Cheers

**Comment by donmccurdy** [comment]
Hi @OldManMeta! This /view package is helpful if you need to preview a glTF model interactively, while the changes are being made. For example, to let a user drag a slider for "opacity" and the model fades in/out in realtime.

For a preset pipeline like Draco compression, you probably don't need the /view package, and the glTF Transform /core + /extensions packages should be enough. Most people use only the [CLI tool](https://gltf-transform.donmccurdy.com/cli.html). A smaller number of people use the /core, /extensions, and /functions modules if they want to write scripts. Very few people use the /view module, since most edits are done offline and not interactively.

Feel free to post questions about the /view module on the main discussions board from glTF Transform too if you want: https://github.com/donmccurdy/glTF-Transform/discussions

**Comment by OldManMeta** [comment]
@donmccurdy Thanks for the response. As per the other question, I'll bring them both together in a discussion and close this out.
Cheers
